name: Publish package to the Maven Central Repository
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: [
            testit-adapter-cucumber4,
            testit-adapter-cucumber5,
            testit-adapter-cucumber6,
            testit-adapter-cucumber7,
            testit-adapter-jbehave,
            testit-adapter-junit4,
            testit-adapter-testng,
            testit-java-commons
        ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          # distribution: 'adopt'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Add permission
        run: chmod +x ./gradlew
      - name: Publish package ${{ matrix.package }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}